<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>launch</string>
		<string>test</string>
	</array>
	<key>name</key>
	<string>Roslaunch</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.roslaunch</string>
	<key>uuid</key>
	<string>a9c17bce-454b-4832-851b-39545aed554c</string>
</dict>
</plist>
